# Generated by Django 6.1.1 on 2026-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_verified',
            field=models.BooleanField(default=False),
        ),
    ]
