# Generated by Django 6.1.1 on 2026-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_emailotp_otp_emailotp_otp_hash_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(default='signup', max_length=30),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(max_length=255),
        ),
    ]
