from django.urls import path
from .views import (
    product_list, 
    category_list, 
    brand_list,
    product_detail,
    create_product,
    update_product,
    delete_product,
    create_category,
    update_category,
    delete_category,
    create_brand,
    update_brand,
    delete_brand,
    create_product_variant,
    update_product_variant,
    delete_product_variant,
    create_product_image,
    delete_product_image,
    create_product_specification,
    delete_product_specification,
    low_stock_products,
)

urlpatterns = [
    path("", product_list, name="product_list"),
    path("<int:product_id>/", product_detail, name="product_detail"),
    path("categories/", category_list, name="category_list"),
    path("brands/", brand_list, name="brand_list"),
    path("create/", create_product, name="create_product"),
    path("<int:product_id>/update/", update_product, name="update_product"),
    path("<int:product_id>/delete/", delete_product, name="delete_product"),
    path("categories/create/", create_category, name="create_category"),
    path("categories/<int:category_id>/update/",update_category,name="update_category"),
    path("categories/<int:category_id>/delete/",delete_category,name="delete_category"),
    path("brands/create/", create_brand, name="create_brand"),
    path("brands/<int:brand_id>/update/",update_brand,name="update_brand"),
    path("brands/<int:brand_id>/delete/",delete_brand,name="delete_brand"),
    path("variants/create/",create_product_variant,name="create_product_variant"),
    path("variants/<int:variant_id>/update/",update_product_variant,name="update_product_variant"),
    path("variants/<int:variant_id>/delete/",delete_product_variant,name="delete_product_variant"),
    path("images/create/",create_product_image,name="create_product_image"),
    path("images/<int:image_id>/delete/",delete_product_image,name="delete_product_image"),
    path("specifications/create/",create_product_specification,name="create_product_specification"),
    path("specifications/<int:specification_id>/delete/",delete_product_specification,name="delete_product_specification"),
    path("admin/low-stock/", low_stock_products, name="low_stock_products"),
]