from rest_framework import serializers
from .models import Payment,Refund


class PaymentSerializer(serializers.ModelSerializer):

    class Meta:
        model = Payment
        fields = [
            "id",
            "user",
            "order",
            "coupon",
            "payment_method",
            "amount",
            "status",
            "created_at",
        ]

        read_only_fields = [
            "id",
            "user",
            "created_at",
        ]

class RefundSerializer(serializers.ModelSerializer):

    class Meta:
        model = Refund
        fields = [
            "id",
            "payment",
            "order",
            "return_request_id",
            "refund_id",
            "amount",
            "gateway",
            "reason",
            "status",
            "created_at",
            "processed_at",
        ]

        # These values are generated by the backend
        read_only_fields = [
            "id",
            "created_at",
            "processed_at",
        ]